### PR TITLE
ADD: Kinetic-Rain website

### PR DESCRIPTION
**Pull request by eito-fis**
Adds the final production build of the kinetic rain website. Also renames to project from `Kinetic-Rain` to `Reuse-Rebuild-React`.

Also not entirely sure that our links are properly handled in this build. It *should* work, but its hard to test locally with the additional github pages URL. If assets aren't loading or links are broken, you can see an up and running version at: https://eito-fis.github.io/kinetic-rain-website

### CODE REVIEW

**Comment by Riya-1** [comment]
Not sure if the name change will work (that'll be a @coreyacl / @amonmillner question) but before I can merge to test, please switch the branch you're doing the PR on to olincollege's `gh-pages` instead of `main`!

**Comment by eito-fis** [comment]
@Riya-1 Changed the branch

**Comment by Riya-1** [comment]
You are now pushing to everyone else's folders...is that intentional?

**Comment by eito-fis** [comment]
Hmm, It might be because I fetched from main once. I'll open another request without them.

**Pull request closed without merging**
